#!/usr/bin/env python3

# Created by: Adam Diwani
# Created on: December 7, 2020
# This program sees if the user actually entered a number
import random


def main():
    #this program doesn't allow it to crash
    
    #input
    magic_number_string = input("Enter a number between 1-10: ")
    
    #process
    try:
        magic_number = int(magic_number_string)
        
        random_number = random.randint(0,9)
        
        if magic_number == random_number:
        #Output
            print("")
            print("correct!")
        else:
            #output
            print("Wrong number. The correct answer was {}".format(random_number))
        
    except Exception:
        print("This is not a number")

if __name__ == "__main__":
    main()
